{{- if and .Values.connectors.enabled (eq .Values.connectors.inbound.mode "credentials") }}
{{- $secretName := include "connectors.authCredentialsSecretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
type: Opaque
data:
  connectors-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "connectors-secret" "length" 10 "providedValues" (list "connectors.inbound.auth.existingSecret") "context" $) }}
{{- end }}
