{{- if .Values.connectors.enabled -}}
{{- if .Values.connectors.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connectors.serviceAccountName" . }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
  {{- with .Values.connectors.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
