apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trident

helmCharts:
  - name: trident-operator
    # Accepts a string. The URL used to locate the chart
    repo: https://github.com/NetApp/trident
    # Accepts a string. The version of the chart
    version: 23.10.0
    # Accepts a string. Replaces RELEASE_NAME in the chart template output
    releaseName: trident-operator
    # Accepts a string. Sets the target namespace
    # for a release (.Release.Namespace in the template)
    namespace: trident
    # Accepts a string. ValuesFile is a local file path or a remote URL to a
    # values file to use instead of the default values that accompanied the chart.
    # The default values are in CHART_HOME/NAME/values.yaml.
    valuesFile: ./values_trident.yaml
    # Accepts merge, override, (default), or replace.
    # ValuesMerge specifies how to treat ValuesInline with respect to Values.
    valuesMerge: override
    # Accepts true or false. Specifies if Helm should also generate
    # CustomResourceDefinitions. The default value false.
    includeCRDs: false
    # Based on the chart https://github.com/NetApp/trident
