apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: keycloak
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
