apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix:  dev-
resources:
- ../../base

patches:
    #patch: |-
      #- op: replace
        #path: /spec/replicas
        #value: 2
  - target:
      kind: IPAddressPool
      name: longhorn-pool-sr3
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 90.190.54.242-90.190.54.242
      - op: replace
        path: /metadata/namespace
        value: metallb-system
  - target:
      kind: IPAddressPool
      name: longhorn-pool-sr6
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 194.106.115.178-194.106.115.178
      - op: replace
        path: /metadata/namespace
        value: metallb-system
  - target:
      kind: L2Advertisement
      name: longhorn-pool-sr3
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: metallb-system
  - target:
      kind: L2Advertisement
      name: longhorn-pool-sr6
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: metallb-system
