{{- if and .Values.operate.enabled .Values.operate.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operate.serviceAccountName" . }}
  labels: {{- include "operate.labels" . | nindent 4 }}
  {{- with .Values.operate.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
