apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    type: local
spec:
  storageClassName: ontap-nas-auto-export
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce