apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trident-pvc
  namespace: trident
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ontap-nas-auto-export
  volumeMode: Filesystem
