apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coroot

#resources:
#- keycloak_v_18.4.0.yaml

helmCharts:
- name: coroot # Accepts a string. The name of the chart. This field is required.
  # Accepts a string. The URL used to locate the chart
  repo: https://coroot.github.io/helm-charts
  #- https://github.com/jboss-dockerfiles/keycloak
  #   - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  # Accepts a string. The version of the chart
  version: 0.3.11
  # Accepts a string. Replaces RELEASE_NAME in the chart template output
  releaseName: coroot
  # Accepts a string. Sets the target namespace
  # for a release (.Release.Namespace in the template)
  namespace: coroot
  # Accepts a string. ValuesFile is a local file path or a remote URL to a
  # values file to use instead of the default values that accompanied the chart.
  # The default values are in CHART_HOME/NAME/values.yaml.
  valuesFile: ./values.yaml
  # Accepts merge, override, (default), or replace.
  # ValuesMerge specifies how to treat ValuesInline with respect to Values.
  valuesMerge: override
  # Accepts true or false. Specifies if Helm should also generate
  # CustomResourceDefinitions. The default value is false.
  includeCRDs: yes
  #dependencies:
  # - name: postgresql
  #    version: 10.16.2
  #    repository: https://charts.bitnami.com/bitnami
  #    condition: postgresql.enabled
