apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
    app.kubernetes.io/instance: longhorn
    component: longhorn-gui
  annotations:
    metallb.universe.tf/address-pool: longhorn-pool-sr6
  name: longhorn-site-2
  namespace: longhorn-argocd
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: longhorn-ui
  type: LoadBalancer
