apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix:  dev-
resources:
- ../../base
- ./pvc-data-mariadb-0.yaml

patches:
  # Replicas for longhorn deployment
  - path: ./patches/json/resourcelimits/replace-resource-limits-keycloak.json
    target:
      kind: StatefulSet
      name: keycloak
      namespace: keycloak