apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-keycloak-db-0
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
