apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mariadb-0
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
