apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mariadb-0
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ontap-nas-auto-export
  volumeMode: Filesystem
