{{- if  and .Values.prometheusServiceMonitor.enabled  .Values.operate.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-operate
  labels: {{- include "camundaPlatform.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
      app.kubernetes.io/component: operate
  endpoints:
    - honorLabels: true
      {{- if .Values.operate.ingress.enabled }}
      path: /actuator/prometheus
      {{- else }}
      path: {{ .Values.operate.contextPath }}/actuator/prometheus
      {{- end }}
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
