apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-keycloak-db-sr3-1
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: pv-grstgworker03-7

