{{- if .Values.console.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - port: {{ .Values.console.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "console.matchLabels" . | nindent 4 }}
{{- end }}
