{{- if and (.Values.global.identity.keycloak.url).host .Values.global.identity.keycloak.internal -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.keycloak.service" . }}
  labels: {{- include "identity.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations}}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: ExternalName
  externalName: {{ .Values.global.identity.keycloak.url.host }}
{{- end -}}
