apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sr6

resources:
- ../../common

patches:
  # patch topology zones
  - path: ../../../../shared-patches/json/rename-node-selector-topology-zone-sr6.json
    target:
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
  - path: ../../../../shared-patches/json/rename-node-selector-topology-zone-sr6.json
    target:
      kind: Deployment
      name: nginx
      namespace: keycloak
  - path: ../../../../shared-patches/json/rename-node-selector-topology-zone-sr6.json
    target:
      kind: StatefulSet
      name: keycloak-db
      namespace: keycloak
  - path: ../../../../shared-patches/json/add-startup-sequence-mariadb-sr6.json
    target:
      kind: StatefulSet
      name: keycloak-db
      namespace: keycloak
  - path: ../../../../shared-patches/json/remove-keycloak-db-annotations.json
    target:
      kind: StatefulSet
      name: keycloak-db
      namespace: keycloak

  # metal-lb changes
  - path: ../../../../shared-patches/json/restore-metallb-namespace-value.json
    target:
      kind: IPAddressPool
      name: keycloak-pool
      namespace: metallb-system
  - path: ../../../../shared-patches/json/restore-metallb-namespace-value.json
    target:
      kind: L2Advertisement
      name: keycloak-pool
      namespace: metallb-system
  - path: ../../../../shared-patches/json/replace-keycloak-pool-ipaddresspool-value-sr6.json
    target:
      kind: L2Advertisement
      name: keycloak-pool
      namespace: metallb-system
  - path: ../../../../shared-patches/json/add-l2advertisement-node-selector-topology-zone-sr6.json
    target:
      kind: L2Advertisement
      name: keycloak-pool
      namespace: metallb-system
  - path: ../../../../shared-patches/json/replace-nginx-service-metallb-annotation-sr6.json
    target:
      kind: Service
      name: nginx
      namespace: keycloak
  - target:
      kind: IPAddressPool
      name: keycloak-pool
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 194.126.105.76/32
