apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: keycloak
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: 125m
            memory: 256Mi
          requests:
            cpu: 75m
            memory: 256Mi
