apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: 04-addusers
spec:
  mariaDbRef:
    name: mariadb
  inheritMetadata:
    annotations:
      database.myorg.io: mariadb
  podMetadata:
    labels:
      sidecar.istio.io/inject: "false"
  serviceAccountName: sqljob
  username: demo-user
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: talkk8s
  sql: |
    CREATE TABLE IF NOT EXISTS users (
      id bigint PRIMARY KEY AUTO_INCREMENT,
      username varchar(255) NOT NULL,
      UNIQUE KEY name__unique_idx (username)
    );
    INSERT INTO users(username) VALUES('mmontes11') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('Vidalee')
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('macno') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('eloylp') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('ksankeerth') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('stefan-bergstein') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('ola-gustafsson') 
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO users(username) VALUES('mo-salah') 
      ON DUPLICATE KEY UPDATE id=id;
    --To be continued, contribute to mariadb-operator! 🦭
