apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    mariadb-password: AgBQopYouphNP7PpfOhk7DIEG8X1QnDA7z7fLPIj8fQmxWUboQzuEeTc0n2uHW1UIts+Ly4zSqeY2ts6RAy7FXF5w2+R+dbB5LuGotP+6a93X/Mi9T4lxf6xzDR7S6fvTx8TIXtPrSIKlwoWF2Q4X8Ms8WfGd/+ua0CWW9xUWDwE9DiSLQqaSn75XSO81ZKoovT447JBwA1/rAqrTHVOFo7+ROBGBBIEWcHEtD7+xXGGAYjS5/aizTjH249pPBmA/Zir1fh4nXTWiXOLvuvGFrexV6X9w3An05akv7jHTzdQzIs4Ep2x/3jhphqtvtJHFepmFN5QieeP9dG9VdJn8nYu2Ie+4tyHPl3wq0bTbmlxKMpss5XzUdSfLkXBBTWLxMAP2RuKybhhZGPmPOUQifNH2oVOWAKOL+BM6rA++zvHXRA4TWT5d6CaVHADTXqRVlPsjoZcAqd54ZohpdZ7bPeB49558RJ8dLSAgWHh4nzlu58AxrcyN8FU6Oi6MMCrEMgUnHoCJIRznNysBr9XH67dtFCVuOloiCwcM9Jjs3vFKBKLDkYAbgtDlQMi7Wjkou5FFfunYulUMH71SLNc3L+dTl9vUv2z0KfcpQ1x2IMJZPkdlEhzvDRvwTuZRhuc+ZOLPIODSqmrBOH8VMM31IKoMg7wacPQ4tfVH5UfukHvkTbTwuZgQ7OHj4WlXn4j90Hdr8zS/ahvT7zP3IzksuI=
    mariadb-galera-mariabackup-password: AgByhs8FjzPmeZlxZYnHS7kZKsemlzYK5xbXwIauObh190Yy71SwSj/784F+o6l2gPw9BI4GIQE4Jn3g0qDsTxpKYrXjXjbPmSavUeZvM2MiSyLr4Y2kU7x+hnLVPqVOb7Q4eovcJIaVTXPA36TtzmJdnyToZS+k7mdhDhEI6mGio6/f3et5ucK2ssK3d/KEX+OazMae8xIVZUer/igw5FQ6VI/q+Ertj+KCuDWC9Bor8ditapR257l/YIu4pmwJmKfmFzXoBq7RNETwhTH0EAq6d9v7zmRyZLf6htjTSXwPJnlQwXqHqg6vikUxotg1EP5T9uvdvjKWA1z4hdFpEqlQvJ+GydFwWTg2x65q6ktt6weehUXJw9TK6T0yVfs6oEjaYXFCe9h59EmBNF2QksZZPt41Eg7Z5waX9DIjMZ8NNTLqbBLRerg7QLipm7s7S4oM560+FKeVdw7YYtR1sWF2B/w0Y3Qcc4vRVpQYiL/PpSjc2Ys5/0/aYfUPVdXUc3zGjbzDbYqpndkT8LeRUBKwBsyx2GkIlCYfsvAjmxvK9Bo+/Z6keaf81TZmq0IwoGwgmwN7B7dBZWqg6WvpP1Kgq7QwL+G3UiQ5CLtqFZjkJr1+FDtZ//NmSVhGmk5NU2Fy+Sd22wAdqLgh6tRxkX0YeCnXLr/Bseqt6vynNib5pdGW+smkLoQHsL/Kz4GO+X/TS88uQHc2xjyKuAYAW082
    mariadb-root-password: AgBOaN1tyDvhbSFf/TSqO1Yk9hpjFlXXwb/CWJjIYRLadOlYhsy//QuaE6T5JXw8E7l0c74DMza/tD+7aYawhoofWYclEqzXuoeXpReHpTJnnpwf52Wp6iLyu05uSG47cLbm59ehBuE9BlH5VWPlhFESGc4pF6dM6d6rzo9Zi2rX78sxicYP5qkrjW5W0o6uUX+iXbjzHVaA8Q9FAue7HKjnGtyUs3PyHSwL8oA9BuIRpUosLeM/b3qG3wPFFmeoBZP2f8oS5vuX1wFF7v7W+S0CwY2zIDarZ6ZosVYMZ94XBat4MFxfqL9Hp5TpqS7WK7mdDag1j9Yp/tusN6vdudhR6hieFu6mMKn7GrY0v2ssEcntR87pGawofx01S3hB5kahL4BQEJcSvXLTHUcLwf8+fBMuUwWy2eAomOV2Uiagz6tDl811qUAqZglhV7EtsQPD0K25SZzyXPasTwR0HruFP48dKUlFOvoJ9SolyytxpKEnwgmy8JOmaMe2sLwWHhvjsQ337C6PqKKolgmGERtGDWBHmBiC9W44+MRMm7Me5AWgPF0zTTNRrfFk3vKBqXS2stHfIkgUowuOFFUE5IsBm+5h1O8fXaeiLKWPJa9b8ccDOPlYdsCywkqiBeKgASDh0JZK77h9RB3zpmRzS8nlppKC2rVK1snoXvSHJOr9OuLM+lSZJvYjdgka9/ZZBUN/2KQHnUOrHhrQ+giYyD7m5Mlx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        version/keycloak-db-secret: "v1"
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque

