apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

patchesStrategicMerge:
  - patch-resource-limits-keycloak.yaml
  - patch-resource-limits-mariadb.yaml
  - patch-resource-limits-nginx.yaml

patches:
  # Patch replicas
  - path: ../../../shared-patches/json/replace-spec-replicas-to-2.json
    target:
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
  - path: ../../../shared-patches/json/replace-spec-replicas-to-2.json
    target:
      kind: Deployment
      name: nginx
      namespace: keycloak
  - path: ../../../shared-patches/json/replace-spec-replicas-to-1.json
    target:
      kind: StatefulSet
      name: keycloak-db
      namespace: keycloak

  # Remove nodePort attr from services
  - path: ../../../shared-patches/json/remove-service-0-attr-nodeport.json
    target:
      kind: Service
      name: keycloak-db
      namespace: keycloak

  # add common environment variables for keycloak
  - target:
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: KC_HOSTNAME
          value: "grstgkeycloak.estpak.ee"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: KC_HOSTNAME_ADMIN
          value: "grstgkeycloak.estpak.ee"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: KC_LOG_LEVEL
          value: "INFO,io.quarkus.vertx.http:TRACE"
