apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:

  #############################################################################
  ########################### Patch Deployment ###############################
  #############################################################################
  # patch replicas 
  - path: ../../../shared-patches/json/replace-spec-replicas-to-2.json
    target:
      kind: Deployment
      name: velero
      namespace: velero

  # patch resource limit sr3
  - path: ./patches/json/replace-resource-limits.json
    target:
      kind: Deployment
      name: velero
      namespace: velero

