apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component



patches:

  #############################################################################
  ########################### Patch Daemonset #################################
  #############################################################################
  # patch resource limit 
  - path: ./patches/json/replace-resource-limits.json
    target:
      kind: DaemonSet
      name: node-agent
      namespace: velero
