apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-operator
  namespace: default
  labels:
    app: k8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-operator
  template:
    metadata:
      labels:
        app: k8s-operator
    spec:
      serviceAccountName: k8s-operator
      containers:
      - name: operator
        image: k8s-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL