apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-release
  labels:
    {{- include "camundaPlatform.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  {{- /* NOTE: the "info" config will be simplified when we fully moved to a flat-chart structure */}}
  info: |
    {{- include "camundaPlatform.releaseInfo" . | nindent 4 }}
