{{- if and (.Values.global.identity.auth.enabled) (or (not .Values.global.identity.auth.connectors.existingSecret) (typeIs "string" .Values.global.identity.auth.connectors.existingSecret)) }}
{{- $secretName := include "camundaPlatform.identitySecretName" (dict "context" . "component" "connectors") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "camundaPlatform.identityLabels" . | nindent 4 }}
type: Opaque
data:
  connectors-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "connectors-secret" "length" 10 "providedValues" (list "global.identity.auth.connectors.existingSecret") "context" $) }}
{{- end }}
