{{- if and (.Values.global.identity.auth.enabled) (or (not .Values.global.identity.auth.operate.existingSecret) (typeIs "string" .Values.global.identity.auth.operate.existingSecret)) }}
{{/*{{- if and (.Values.global.identity.auth.enabled) (not .Values.global.identity.auth.operate.existingSecret) }}*/}}
{{- $secretName := include "camundaPlatform.identitySecretName" (dict "context" . "component" "operate") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "camundaPlatform.identityLabels" . | nindent 4 }}
type: Opaque
data:
  operate-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "operate-secret" "length" 10 "providedValues" (list "global.identity.auth.operate.existingSecret") "context" $) }}
{{- end }}
